 const API = {
    login: "/admin/login",
    DashBoard: "/dashboard/business_info",
    getIds:"/required_ids",
    search:"/search",
    sendGift:"/dashboard/users/send_gift",
    addCity: "/dashboard/countries/cities",
    addEvent: "/dashboard/cities/events",
    addGT: "/dashboard/group_trip",
    addGuide: "/dashboard/guides/store",
    cities: "/dashboard/cities",
    users: "/dashboard/users/",
    eventStatus:"/dashboard/event/",
    Guides:"/dashboard/guides",
    Guide:"/guides/" ,
    Ev_GT:'/dashboard/events_and_groups',
    City:'/cities/',
    UpdateCity:'/dashboard/cities/',
    UpdateGuide:'/dashboard/guides/',
    feedBack: '/feedback/',
};
export default API;
